services:
  user-postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9011"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - minio_data:/data
    ports:
      - "9010:9000"
      - "9011:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
        
  multi-agent-system:
    build:
      context: agents/
      dockerfile: Dockerfile
    image: magnusdtd/naver-hkt-agent
    ports:
      - "8000:8000"
    depends_on:
      user-postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}
      CLOVASTUDIO_API_KEY: ${CLOVASTUDIO_API_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      CLOVA_OCR_SECRET: ${CLOVA_OCR_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MLFLOW_URI: ${MLFLOW_URI}

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    image: magnusdtd/naver-hkt-frontend
    ports:
      - "8070:8070"


volumes:
  postgres_data:
  minio_data:
