{{- if .Values.agentSystem.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "naver-hkt.name" . }}-agent-system
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naver-hkt.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-system
spec:
  type: {{ .Values.agentSystem.service.type }}
  ports:
  - port: {{ .Values.agentSystem.service.port }}
    targetPort: {{ .Values.agentSystem.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "naver-hkt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent-system
{{- end }}
