{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "naver-hkt.name" . }}-minio
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naver-hkt.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
  - name: api
    port: {{ .Values.minio.service.apiPort }}
    targetPort: {{ .Values.minio.service.apiPort }}
    protocol: TCP
  - name: console
    port: {{ .Values.minio.service.consolePort }}
    targetPort: {{ .Values.minio.service.consolePort }}
    protocol: TCP
  selector:
    {{- include "naver-hkt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }} 