apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "naver-hkt.name" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naver-hkt.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.backend.env.BASE_URL | quote }}
  DATABASE_URL: {{ include "naver-hkt.databaseUrl" . | quote }}
  MINIO_URL: {{ include "naver-hkt.minioUrl" . | quote }}
  MINIO_ENDPOINT: {{ include "naver-hkt.minioUrl" . | quote }}