{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "naver-hkt.name" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naver-hkt.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "naver-hkt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }} 